
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        "fastmcp==2.13.0.2" \
        "mcp[cli]==1.19.0" \
        "google-genai>=0.4.0" \
        "python-dotenv==1.2.0" \
        "pydantic==2.12.3"


COPY . .

CMD ["python", "gemini_integration.py"]