# [1] 서버 배포 (Deployment)
# 뉴스 수집 및 프롬프트를 제공하는 지식 베이스 서버
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-server
  template:
    metadata:
      labels:
        app: news-server
    spec:
      containers:
      - name: server
        # Docker Hub에 업로드된 서버용 이미지 (v2)
        image: qwer319/ai-news-server:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: NAVER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: NAVER_CLIENT_ID
        - name: NAVER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: NAVER_CLIENT_SECRET
        # 로그 즉시 출력을 위한 설정
        - name: PYTHONUNBUFFERED
          value: "1"

---

# [2] 서버 서비스 (Service)
# 클라이언트가 이 이름(mcp-server-svc)으로 서버를 찾음
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-svc
spec:
  type: ClusterIP
  selector:
    app: news-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: mcp-client
spec:
  containers:
  - name: client
    # Docker Hub에 업로드된 클라이언트용 이미지 (v2)
    image: qwer319/ai-news-client:v2
    imagePullPolicy: Always
    
    # [핵심] 대화형 모드 활성화 (kubectl attach 접속용)
    stdin: true
    tty: true
    
    env:
    # Service 이름을 이용한 내부 통신 주소 (/mcp 경로 사용)
    - name: MCP_SERVER_URL
      value: "http://mcp-server-svc:8000/mcp"
    
    # Gemini API 키 주입
    - name: GEMINI_API_KEY
      valueFrom:
        secretKeyRef:
          name: mcp-secrets
          key: GEMINI_API_KEY
    
    - name: PYTHONUNBUFFERED
      value: "1"